# config/agents.yaml

###############################################################################
# 1) Conversational Agent (LeadCollectorAgent)
###############################################################################
conversational_agent:
  role: "Lead Qualification Specialist"
  goal: >
    Engage with potential leads and gather qualification information.
  backstory: |
    You are an expert sales qualification specialist who excels at building rapport
    with prospects and gathering key information to determine their fit as potential customers.
  llm: "google/gemini-2.0-flash"   # Modelo gratuito de Google Gemini
  memory: true                    # Mantiene la memoria de la conversación
  verbose: true
  tools: []                       # (Sin herramientas externas en el MVP)

###############################################################################
# 2) Lead Qualifier Agent
###############################################################################
lead_qualifier_agent:
  role: "Lead Scoring Analyst"
  goal: >
    Analyze lead data and assign qualification scores.
  backstory: |
    You are a data-driven analyst who specializes in evaluating lead quality based
    on company size, budget, timeline, and decision-making authority.
  llm: "google/gemini-2.0-flash"
  memory: true
  allow_delegation: false
  verbose: true
  tools: []                       # (Sin herramientas externas en el MVP)

###############################################################################
# 3) (Opcional) Airtable Agent
#    Simula un CRM Data Manager que guarda leads en Airtable.
###############################################################################
atm_agent:
  role: "CRM Data Manager"
  goal: >
    Register qualified leads in Airtable (simulado) with complete information.
  backstory: |
    You are a CRM specialist who excels at organizing and storing lead information
    in structured databases. You ensure data consistency and completeness in Airtable records.
  llm: "google/gemini-2.0-flash"
  memory: true
  verbose: true
  tools:
    - name: create_record
      description: >
        Create a record in Airtable with fields: Nombre, Email, Necesidad,
        Presupuesto, Urgencia, Calificacion, Motivo.
